LOCAL_PATH := $(call my-dir)

# OnePlus Camera
include $(CLEAR_VARS)
LOCAL_MODULE := GCam
LOCAL_MODULE_OWNER := google
LOCAL_SRC_FILES := apk/$(LOCAL_MODULE).apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Camera2 Snap
include $(BUILD_PREBUILT)
